/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package estetica;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;


public class clientes extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    int id;
    public clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombrestxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apaternotxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        amaternotxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefonotxt = new javax.swing.JTextField();
        regbtn = new javax.swing.JButton();
        busbtn = new javax.swing.JButton();
        aceptbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        clientelbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sexolist = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cliente Actual:");

        jLabel2.setText("Nombre(s):");

        nombrestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrestxtActionPerformed(evt);
            }
        });
        nombrestxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombrestxtKeyTyped(evt);
            }
        });

        jLabel3.setText("Apellido Paterno:");

        apaternotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apaternotxtKeyTyped(evt);
            }
        });

        jLabel4.setText("Apellido Materno:");

        amaternotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amaternotxtKeyTyped(evt);
            }
        });

        jLabel5.setText("Telefono:");

        telefonotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonotxtKeyTyped(evt);
            }
        });

        regbtn.setText("Registrar");
        regbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtnActionPerformed(evt);
            }
        });

        busbtn.setText("Buscar");
        busbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busbtnActionPerformed(evt);
            }
        });

        aceptbtn.setText("Seleccionar");
        aceptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptbtnActionPerformed(evt);
            }
        });

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Sexo:");

        sexolist.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F", "M" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(apaternotxt)
                                                    .addComponent(amaternotxt)
                                                    .addComponent(nombrestxt)
                                                    .addComponent(clientelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(telefonotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(67, 67, 67)
                                        .addComponent(sexolist, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(0, 68, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(regbtn)
                                .addGap(11, 11, 11)
                                .addComponent(busbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aceptbtn))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombrestxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apaternotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amaternotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sexolist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telefonotxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clientelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regbtn)
                    .addComponent(busbtn)
                    .addComponent(aceptbtn))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtnActionPerformed
if(!apaternotxt.getText().isEmpty()&&!amaternotxt.getText().isEmpty()&& !nombrestxt.getText().isEmpty()&&!telefonotxt.getText().isEmpty()){
            conectar con=new conectar();
            
            ResultSet resultado;
           resultado=con.buscar("select * from clientes where apaterno='"+apaternotxt.getText()+"' and amaterno='"+amaternotxt.getText()+"' and nombres='"+nombrestxt.getText()+"'");
            try {
                         if(resultado.next()){
                             JOptionPane.showMessageDialog(rootPane, "El usuario ya existe");
                        
                             }
                        else{
                      con.agregar("insert into clientes (id, apaterno, amaterno, nombres, sexo, telefono) values (null, '"+apaternotxt.getText()+"', '"+amaternotxt.getText()+"', '"+nombrestxt.getText()+"','"+sexolist.getSelectedIndex()+"', '"+telefonotxt.getText()+"')");
      JOptionPane.showMessageDialog(rootPane, "Los datos han sido guardados correctamente");
                         
                         }
           
             
            }
                          catch (SQLException ex) {
                 JOptionPane.showMessageDialog(rootPane, "Error al buscar3");

            } 
            
        }       
else{
     JOptionPane.showMessageDialog(rootPane, "Todos los campos son obligatorios");
}
    }//GEN-LAST:event_regbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
     Inicio inicio=new Inicio(id);
     inicio.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombrestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrestxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrestxtActionPerformed

    private void nombrestxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrestxtKeyTyped
        int k=(int)evt.getKeyChar();
    if (k == 'a' || k == 'A' || k == 'b' || k == 'B' || k == 'c' || k == 'C'|| k == 'd' || k == 'D'|| k == 'e' || k == 'E'|| k == 'f' || k == 'F'|| k == 'g' || k == 'G'|| k == 'h' || k == 'H'|| k == 'i' || k == 'I'|| k == 'j' || k == 'j'|| k == 'k' || k == 'K'|| k == 'l' || k == 'L'|| k == 'm' || k == 'M'|| k == 'n' || k == 'N'|| k == 'ñ' || k == 'Ñ'|| k == 'o' || k == 'O'|| k == 'p'|| k == 'P'|| k == 'q' || k == 'Q'|| k == 'r' || k == 'R'|| k == 's' || k == 'S'|| k == 't' || k == 'T'|| k == 'u' || k == 'U'|| k == 'v' || k == 'V'|| k == 'w' || k == 'W'|| k == 'x' || k == 'X'|| k == 'y' || k == 'Y'|| k == 'z' || k == 'Z'|| k == ' '  ){ 
        
        if(nombrestxt.getText().length()>=25){
            evt.consume();
        }
    }else{
        evt.consume();
    }
    }//GEN-LAST:event_nombrestxtKeyTyped

    private void apaternotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apaternotxtKeyTyped
        int k=(int)evt.getKeyChar();
    if (k == 'a' || k == 'A' || k == 'b' || k == 'B' || k == 'c' || k == 'C'|| k == 'd' || k == 'D'|| k == 'e' || k == 'E'|| k == 'f' || k == 'F'|| k == 'g' || k == 'G'|| k == 'h' || k == 'H'|| k == 'i' || k == 'I'|| k == 'j' || k == 'j'|| k == 'k' || k == 'K'|| k == 'l' || k == 'L'|| k == 'm' || k == 'M'|| k == 'n' || k == 'N'|| k == 'ñ' || k == 'Ñ'|| k == 'o' || k == 'O'|| k == 'p'|| k == 'P'|| k == 'q' || k == 'Q'|| k == 'r' || k == 'R'|| k == 's' || k == 'S'|| k == 't' || k == 'T'|| k == 'u' || k == 'U'|| k == 'v' || k == 'V'|| k == 'w' || k == 'W'|| k == 'x' || k == 'X'|| k == 'y' || k == 'Y'|| k == 'z' || k == 'Z'|| k == ' '  ){ 
        
        if(apaternotxt.getText().length()>=15){
            evt.consume();
        }
    }else{
        evt.consume();
    }
    }//GEN-LAST:event_apaternotxtKeyTyped

    private void amaternotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amaternotxtKeyTyped
       int k=(int)evt.getKeyChar();
    if (k == 'a' || k == 'A' || k == 'b' || k == 'B' || k == 'c' || k == 'C'|| k == 'd' || k == 'D'|| k == 'e' || k == 'E'|| k == 'f' || k == 'F'|| k == 'g' || k == 'G'|| k == 'h' || k == 'H'|| k == 'i' || k == 'I'|| k == 'j' || k == 'j'|| k == 'k' || k == 'K'|| k == 'l' || k == 'L'|| k == 'm' || k == 'M'|| k == 'n' || k == 'N'|| k == 'ñ' || k == 'Ñ'|| k == 'o' || k == 'O'|| k == 'p'|| k == 'P'|| k == 'q' || k == 'Q'|| k == 'r' || k == 'R'|| k == 's' || k == 'S'|| k == 't' || k == 'T'|| k == 'u' || k == 'U'|| k == 'v' || k == 'V'|| k == 'w' || k == 'W'|| k == 'x' || k == 'X'|| k == 'y' || k == 'Y'|| k == 'z' || k == 'Z'|| k == ' '  ){ 
        
        if(amaternotxt.getText().length()>=15){
            evt.consume();
        }
    }else{
        evt.consume();
    }
    }//GEN-LAST:event_amaternotxtKeyTyped

    private void telefonotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonotxtKeyTyped
        int k=(int)evt.getKeyChar();
    if (k == '0' || k == '1' || k == '2' || k == '3' || k == '4' || k == '5'|| k == '6' || k == '7'|| k == '8' || k == '9'){ 
        
        if(telefonotxt.getText().length()>=10){
            evt.consume();
        }
    }else{
        evt.consume();
    }
    }//GEN-LAST:event_telefonotxtKeyTyped

    private void aceptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptbtnActionPerformed
        if(!apaternotxt.getText().isEmpty()&&!amaternotxt.getText().isEmpty()&& !nombrestxt.getText().isEmpty()){
            conectar con=new conectar();
            
            ResultSet resultado;
           resultado=con.buscar("select * from clientes where apaterno='"+apaternotxt.getText()+"' and amaterno='"+amaternotxt.getText()+"' and nombres='"+nombrestxt.getText()+"'");
            try {
                         if(resultado.next()){
                          id=resultado.getInt("id");
                          
                          
            
            
           resultado=con.buscar("select * from clientes where id='"+id +"'");
            try {
                         if(resultado.next()){
                             clientelbl.setText(resultado.getString("apaterno")+" "+resultado.getString("amaterno")+" "+resultado.getString("nombres"));
                             }
                   }
                          catch (SQLException ex) {
               }
                             }
                        else{
       JOptionPane.showMessageDialog(rootPane, "El usuaio no existe");
                         
                         }
           
             
            }
                          catch (SQLException ex) {
                 JOptionPane.showMessageDialog(rootPane, "Error al buscar3");

            } 
            
        }       
else{
     JOptionPane.showMessageDialog(rootPane, "Los campos Nombre(s), Apellido Paterno y Apellido Materno son obligatorios");
}
    }//GEN-LAST:event_aceptbtnActionPerformed

    private void busbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busbtnActionPerformed
        if(!apaternotxt.getText().isEmpty()&&!amaternotxt.getText().isEmpty()&& !nombrestxt.getText().isEmpty()){
            conectar con=new conectar();
            
            ResultSet resultado;
           resultado=con.buscar("select * from clientes where apaterno='"+apaternotxt.getText()+"' and amaterno='"+amaternotxt.getText()+"' and nombres='"+nombrestxt.getText()+"'");
            try {
                         if(resultado.next()){
                             nombrestxt.setText(resultado.getString("nombres"));
                             apaternotxt.setText(resultado.getString("apaterno"));
                             amaternotxt.setText(resultado.getString("amaterno"));
                             sexolist.setSelectedIndex(resultado.getInt("sexo"));
                             telefonotxt.setText(resultado.getString("telefono"));
                             }
                        else{
       JOptionPane.showMessageDialog(rootPane, "El usuaio no existe");
                         
                         }
           
             
            }
                          catch (SQLException ex) {
                 JOptionPane.showMessageDialog(rootPane, "Error al buscar3");

            } 
            
        }       
else{
     JOptionPane.showMessageDialog(rootPane, "Los campos Nombre(s), Apellido Paterno y Apellido Materno son obligatorios");
}
    }//GEN-LAST:event_busbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new clientes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptbtn;
    private javax.swing.JTextField amaternotxt;
    private javax.swing.JTextField apaternotxt;
    private javax.swing.JButton busbtn;
    private javax.swing.JLabel clientelbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombrestxt;
    private javax.swing.JButton regbtn;
    private javax.swing.JComboBox sexolist;
    private javax.swing.JTextField telefonotxt;
    // End of variables declaration//GEN-END:variables
}
